themes/ixtheo2/theme.config.php
(tuefind also inherits bootstrap3, and adds certain helper functions)
=> ixtheo2 inherits from tuefind instead of bootstrap3

local/tuefind/instances/bibstudies/config/vufind/config.ini, local/tuefind/instances/ixtheo/config/vufind/config.ini, local/tuefind/instances/krimdok/config/vufind/config.ini, local/tuefind/instances/relbib/config/vufind/config.ini, module/IxTheo/config/module.config.php, module/TueFind/config/module.config.php, module/TueFind/src/TueFind/Controller/FeedbackController.php
notes:
- changed ixtheo "tab_enabled = false" to ";tab_enabled = true", cause it's the same and default
- Factory itself is generic, so no need to move anything from IxTheo to TueFind as well
=> changes to FeedbackController

module/TueFindSearch/src/TueFindSearch/Backend/Solr/Backend.php, module/TueFindSearch/src/TueFindSearch/Backend/Solr/QueryBuilder.php, module/TueFindSearch/src/TueFindSearch/Backend/Solr/Response/Json/RecordCollection.php, module/TueFindSearch/src/TueFindSearch/Backend/Solr/Response/Json/RecordCollectionFactory.php, module/TueFindSearch/src/TueFindSearch/Service.php
see https://sourceforge.net/p/vufind/mailman/message/36636072/
=> removed closing php tags "?>" and newlines behind them to avoid RSS feed problems

public/robots.txt
ixtheo sitemap: changes to be closer to VuFind recommendations
see https://vufind.org/wiki/administration:robots.txt
=> ixtheo sitemap

themes/relbib2/templates/content/acquisition_profile.phtml, themes/relbib2/templates/content/features_common.phtml, themes/relbib2/templates/content/features_personalised.phtml, themes/relbib2/templates/static/de/PDASubscriptionInfoText.phtml, themes/relbib2/templates/static/en/PDASubscriptionInfoText.phtml, themes/relbib2/templates/static/en/partials/news.phtml, themes/tuefind/templates/static/en/crawler.phtml
(uppercase only if next to FID, else lowercase)
=> religious studies: study of religion

module/TueFind/src/TueFind/RecordDriver/SolrMarc.php, themes/ixtheo/templates/RecordDriver/DefaultRecord/data-reviewed_records.phtml, themes/ixtheo/templates/RecordDriver/DefaultRecord/data-reviews.phtml
... also renamed "reviewer" to "author", because "reviewer" is not correct in all cases
=> links to reviews & reviewed records should not be generated if ppn is missing

local/tuefind/instances/krimdok/config/vufind/NoILS.ini, local/tuefind/instances/krimdok/config/vufind/config.ini
... with similar options like IxTheo
=> User Accounts for KrimDok

local/tuefind/instances/ixtheo/config/vufind/export.ini, local/tuefind/instances/krimdok/config/vufind/export.ini
see:
- changelog for VuFind 5.0: https://vufind.org/wiki/changelog#release_50_-_7_16_2018
- RefWorks API specification: http://www.refworks.com/directexport.htm
=> RefWorks POST mechanism

module/VuFind/src/VuFind/View/Helper/Root/Metadata.php
- Fixes a problem where first matching class would "win" and other vocabularies would be ignored.
=> Refactor vocabulary determination to a separate method.

module/IxTheo/sql/mysql.sql
... found several other problems while working on #1353
=> Solved multiple problems in mysql.sql for IxTheo module

module/IxTheo/src/IxTheo/Controller/RecordController.php, module/IxTheo/src/IxTheo/RecordDriver/SolrDefault.php, module/IxTheo/src/IxTheo/View/Helper/IxTheo/IxTheo.php, themes/ixtheo/templates/RecordDriver/DefaultRecord/result-list.phtml, themes/ixtheo/templates/RecordDriver/DefaultRecord/toolbar.phtml, themes/ixtheo/templates/record/subscribe.phtml, themes/ixtheo2/templates/RecordDriver/DefaultRecord/result-list.phtml, themes/ixtheo2/templates/RecordDriver/DefaultRecord/toolbar.phtml, themes/ixtheo2/templates/static/de/SubscriptionBundles.phtml
=> Improved frontend handling for subscription bundles

module/TueFind/src/TueFind/RecordDriver/SolrAuthMarc.php, module/TueFind/src/TueFind/View/Helper/TueFind/Authority.php, themes/tuefind/templates/authority/record.phtml
Just to don't lose these changes
=> authority (external references)

local/tuefind/instances/relbib/config/vufind/tuefind.ini
This should be merged together with ubtue/ub_tools#3760
=> relbib: Change path to rss_aggregator_relbib.conf

composer.lock
Follow-up to #1423, to keep things consistent.
=> composer.lock: Added elasticsearch/elasticsearch and its dependencies.

themes/relbib2/templates/myresearch/menu.phtml
Lots of copy paste from parent (=ixtheo) template, the changed code is marked with a `` comment section.
=> relbib2: Show RSS feed settings in myresearch/menu.phtml

module/TueFind/sql/mysql.sql
Please merge this PR together with ubtue/ub_tools#3798
=> Add new column "tuefind_uuid" to user table.

import/marc_auth_tuefind.properties, local/tuefind/instances/ixtheo/config/vufind/authority.ini, solr/vufind/authority/conf/schema_tuefind_fields.xml
(also add new "place" field to authority index)
=> enable functions from ubtue/ub_tools#3858

module/TueFind/sql/mysql.sql
belongs to ubtue/ub_tools#3898
=> TueFind/mysql.sql: Fix problem with tuefind_uuid TRIGGER in MariaDB

module/IxTheo/src/IxTheo/Db/Row/PluginManager.php, module/IxTheo/src/IxTheo/Db/Row/User.php, module/IxTheo/src/IxTheo/Db/Table/PluginManager.php, module/IxTheo/src/IxTheo/Db/Table/User.php, module/TueFind/src/TueFind/Db/Table/User.php
- sorted by username
- limited to current instance in IxTheo-environment
=> admin user select

import/index_java/src/org/tuefind/index/TueFindBiblio.java, import/marc_ixtheo.properties, solr/vufind/biblio/conf/schema_ixtheo_fields.xml, solr/vufind/biblio/conf/schema_ixtheo_types.xml
belongs together with ubtue/ub_tools#4070
=> added subsystem field (+ bbox functionality)

import/marc_auth_tuefind.properties, local/tuefind/instances/bibstudies/config/vufind/subsystem.ini, local/tuefind/instances/churchlaw/config/vufind/subsystem.ini, local/tuefind/instances/ixtheo/config/vufind/authority.ini, local/tuefind/instances/ixtheo/config/vufind/subsystem.ini, local/tuefind/instances/relbib/config/vufind/subsystem.ini, module/TueFind/src/TueFind/RecordDriver/SolrAuthMarc.php, themes/tuefind/templates/authority/record.phtml
mergeable, but should wait until #1567 is solved to avoid interrupting the testers
=> authority: Changed "subsystem" mechanism

local/tuefind/instances/ixtheo/config/vufind/sitemap.ini, local/tuefind/instances/relbib/config/vufind/sitemap.ini
=> Include Authority records in ixtheo/relbib sitemaps

module/IxTheo/sql/mysql.sql, module/IxTheo/src/IxTheo/Db/Table/User.php, module/IxTheo/src/IxTheo/Utility.php
For DB migration, see: ubtue/ub_tools#4129
=> IxTheo: Allow username + email per subsystem, add bibstudies + churchlaw subsystems to ixtheo_user_type.

module/TueFind/sql/mysql.sql
This is just the full schema for the installer. After this one is merged, i will create a system_update in ub_tools.
=> TueFind/mysql.sql: Added control_number and terms_date to tuefind_publications

module/IxTheo/src/IxTheo/Db/Table/User.php, module/TueFind/sql/mysql.sql, module/TueFind/src/TueFind/Controller/AdminFrontendController.php, module/TueFind/src/TueFind/Db/Table/User.php, themes/tuefind/templates/adminfrontend/showadmins.phtml, themes/tuefind/templates/myresearch/menu.phtml
This pull request MUST be merged together with ubtue/ub_tools#4213
=> Replace tuefind_is_admin by tuefind_rights

local/tuefind/instances/bibstudies/config/vufind/searches.ini, local/tuefind/instances/churchlaw/config/vufind/searches.ini, local/tuefind/instances/ixtheo/config/vufind/searches.ini, module/IxTheo/src/IxTheo/Search/Backend/Solr/QueryBuilder.php, module/IxTheo/src/IxTheo/Search/Backend/Solr/SearchHandler.php, module/TueFindSearch/src/TueFindSearch/Backend/Solr/QueryBuilder.php, module/TueFindSearch/src/TueFindSearch/Backend/Solr/SearchHandler.php
=> Moved functionality from QueryBuilder to SearchHandler to make that possible
=> Added Ranged Searches to Advanced Searches

module/TueFind/sql/mysql.sql, module/TueFind/src/TueFind/Controller/RedirectController.php, module/TueFind/src/TueFind/Db/Row/User.php, module/TueFind/src/TueFind/Service/KfL.php, themes/tuefind/templates/redirect/license.phtml
belongs together with ubtue/ub_tools#4264
=> License locking mechanism for single users

module/TueFind/sql/mysql.sql
belongs together with ubtue/ub_tools#4278
=> tuefind_rss_feed.active

themes/tuefind/templates/RecordDriver/DefaultRecord/data-onlineAccess.phtml
(will be forced to login when he tries to use it)
=> KfL: Also show link if user is not logged in

themes/ixtheo/templates/Auth/Database/create.phtml
(This was a user request by mail relayed by @thefass)
=> Profile: Also show Username when logged in

local/tuefind/instances/relbib/config/vufind/tuefind.ini, themes/relbib2/templates/content/self_archiving_service.phtml, themes/relbib2/templates/content/self_archiving_service_de.phtml
We should merge this over the next couple of days & put it live before the conference on 4.-8.9.
=> Self-archiving service for RelBib

import/es_fulltext.properties
ub45 should be like ub16
ub55 should be like ub15
so the settings have been wrong all the time!
=> es_fulltext.properties: Switch settings for ub45+ub55

module/IxTheo/src/IxTheo/View/Helper/Root/RecordDataFormatterFactory.php, module/TueFind/src/TueFind/RecordDriver/SolrDefault.php, module/TueFind/src/TueFind/View/Helper/Root/RecordDataFormatterFactory.php, themes/tuefind/templates/RecordDriver/DefaultRecord/data-interlibraryLoan.phtml
Note: This is just a first very simple version for IxTheo, display texts might be changed later so i did not add entries to the translation files yet
=> Add Interlibrary Loan Portal for IxTheo

module/IxTheo/src/IxTheo/RecordDriver/SolrDefault.php, module/IxTheo/src/IxTheo/RecordDriver/SolrMarc.php, module/IxTheo/src/IxTheo/View/Helper/Root/RecordDataFormatterFactory.php, themes/ixtheo/templates/RecordDriver/DefaultRecord/data-collectionsHierarchy.phtml
Works fine but could look better, if you got any ideas please let me know!
Note: The example is from 146649419
=> Add collections to full record view

module/KrimDok/src/KrimDok/RecordDriver/SolrMarc.php
This PR is based on the data created by the change in PR ubtue/ub_tools#4505
=> Albert-Krebs-Library: Display Parent Availability Information

themes/tuefind/templates/Related/AuthorityAuthors.phtml
.. also remove schema.org "sameAs" Property since it is semantically wrong here
=> AuthorityAuthors.phtml: Solve link problem in authority full view for related authors

public/robots/bibstudies.txt, public/robots/churchlaw.txt, public/robots/ixtheo.txt, public/robots/krimdok.txt, public/robots/relbib.txt
today ~50.000 calls from claudebot to URLs like this:
`relbib.de:443 3.145.41.253 - - [23/Jul/2024:11:37:20 +0200] "GET /MyResearch/SaveSearch?save=103475646 HTTP/2.0" 200 8212 "-" "Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko; compatible; ClaudeBot/1.0; +claudebot@anthropic.com)"`
=> robots.txt: Disallow /MyResearch

local/tuefind/instances/krimdok/config/vufind/tuefind.ini
=> tuefind.ini: Include local_overrides/krimdok_kfl.conf

themes/tuefind/templates/search/list-authorfacets.phtml
=> Add fuzzy link to joint/related author if target author has no ID

module/IxTheo/src/IxTheo/View/Helper/IxTheo/IxTheo.php, module/IxTheo/src/IxTheo/View/Helper/Root/RecordDataFormatterFactory.php, module/TueFind/src/TueFind/Service/KfL.php, module/TueFind/src/TueFind/View/Helper/Root/Matomo.php, module/TueFind/src/TueFind/View/Helper/TueFind/TueFind.php
=> VuFind 10.0: Replace deprecated calls to isLoggedIn in Modules

themes/krimdok2/templates/content/fulltexts.phtml, themes/krimdok2/templates/content/fulltexts_de.phtml, themes/krimdok2/templates/content/fulltexts_es.phtml, themes/krimdok2/templates/content/tools.phtml, themes/krimdok2/templates/content/tools_de.phtml, themes/krimdok2/templates/content/tools_es.phtml
Fulltext and tools content for three languages (German, English, and Spanish)
=> Update krimdok content pages

module/TueFind/sql/mysql.sql
belongs together with ubtue/ub_tools#4619
=> Add a new field 'type' to table 'tuefind_rss_feeds'
